# Generated by Django 4.1 on 2024-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientomedicamento',
            name='dosis',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tratamientomedicamento',
            name='frecuencia',
            field=models.CharField(default='', max_length=100),
        ),
    ]
