# Generated by Django 4.1 on 2024-12-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tratamientomedicamento_dosis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
    ]
