# Generated by Django 4.1 on 2024-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_cita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontratamientomedicamento',
            name='dosis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asignaciontratamientomedicamento',
            name='frecuencia',
            field=models.CharField(max_length=50),
        ),
    ]
